version: '3'
services:
  frontend:
    build: ./chatweb-frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./chatweb-backend
    ports:
      - "4000:4000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend

